<?php

function getAchievementDefinitions(): array
{
    return [
        [
            'code' => 'first_win',
            'name' => 'Первая победа',
            'description' => 'Выиграй свою первую игру',
            'icon' => 'bi-trophy-fill',
            'icon_type' => 'bootstrap',
            'category' => 'game',
            'condition_type' => 'wins',
            'condition_value' => 1,
            'rarity' => 'common',
            'sort_order' => 10,
        ],
        [
            'code' => 'social_butterfly',
            'name' => 'Душа компании',
            'description' => 'Добавь 3 друзей',
            'icon' => 'bi-people-fill',
            'icon_type' => 'bootstrap',
            'category' => 'social',
            'condition_type' => 'friends_added',
            'condition_value' => 3,
            'rarity' => 'common',
            'sort_order' => 20,
        ],
        [
            'code' => 'veteran',
            'name' => 'Ветеран',
            'description' => 'Сыграй 50 игр',
            'icon' => 'bi-calendar-check-fill',
            'icon_type' => 'bootstrap',
            'category' => 'milestone',
            'condition_type' => 'games_played',
            'condition_value' => 50,
            'rarity' => 'rare',
            'sort_order' => 30,
        ],
        [
            'code' => 'champion',
            'name' => 'Чемпион',
            'description' => 'Выиграй 10 игр',
            'icon' => 'bi-award-fill',
            'icon_type' => 'bootstrap',
            'category' => 'game',
            'condition_type' => 'wins',
            'condition_value' => 10,
            'rarity' => 'rare',
            'sort_order' => 40,
        ],
        [
            'code' => 'pacifist',
            'name' => 'Миротворец',
            'description' => 'Выиграй в Блокус, никого не заблокировав',
            'icon' => 'bi-shield-check',
            'icon_type' => 'bootstrap',
            'category' => 'game',
            'condition_type' => 'game_event',
            'condition_value' => 0,
            'rarity' => 'uncommon',
            'sort_order' => 50,
        ],
        [
            'code' => 'flash',
            'name' => 'Молния',
            'description' => 'Ответь быстрее чем за 0.5 сек',
            'icon' => 'bi-lightning-fill',
            'icon_type' => 'bootstrap',
            'category' => 'game',
            'condition_type' => 'game_event',
            'condition_value' => 500,
            'rarity' => 'uncommon',
            'sort_order' => 60,
        ],
        [
            'code' => 'brute',
            'name' => 'Вышибала',
            'description' => 'Выгони 3 человек в Бункере',
            'icon' => 'bi-hammer',
            'icon_type' => 'bootstrap',
            'category' => 'game',
            'condition_type' => 'game_event',
            'condition_value' => 3,
            'rarity' => 'uncommon',
            'sort_order' => 70,
        ],
        [
            'code' => 'polyglot',
            'name' => 'Полиглот',
            'description' => 'Сыграй во все типы игр',
            'icon' => 'bi-translate',
            'icon_type' => 'bootstrap',
            'category' => 'milestone',
            'condition_type' => 'polyglot',
            'condition_value' => 1,
            'rarity' => 'rare',
            'sort_order' => 80,
        ],
        [
            'code' => 'night_owl',
            'name' => 'Ночная сова',
            'description' => 'Сыграй игру после 2 часов ночи',
            'icon' => 'bi-moon-stars-fill',
            'icon_type' => 'bootstrap',
            'category' => 'game',
            'condition_type' => 'game_event',
            'condition_value' => 2,
            'rarity' => 'uncommon',
            'sort_order' => 90,
        ],
        [
            'code' => 'strategist',
            'name' => 'Стратег',
            'description' => 'Выиграй в Блокус с отрывом 20+ очков',
            'icon' => 'bi-diagram-3-fill',
            'icon_type' => 'bootstrap',
            'category' => 'game',
            'condition_type' => 'game_event',
            'condition_value' => 20,
            'rarity' => 'rare',
            'sort_order' => 100,
        ],
        [
            'code' => 'survivor',
            'name' => 'Выживший',
            'description' => 'Выиграй в Бункере 3 раза подряд',
            'icon' => 'bi-heart-pulse-fill',
            'icon_type' => 'bootstrap',
            'category' => 'game',
            'condition_type' => 'bunker_streak',
            'condition_value' => 3,
            'rarity' => 'rare',
            'sort_order' => 110,
        ],
        [
            'code' => 'tictactoe_master',
            'name' => 'Мастер Крестиков',
            'description' => 'Выиграй 10 раз в Крестики-Нолики',
            'icon' => 'bi-grid-3x3-gap-fill',
            'icon_type' => 'bootstrap',
            'category' => 'game',
            'condition_type' => 'game_event',
            'condition_value' => 10,
            'rarity' => 'uncommon',
            'sort_order' => 120,
        ],
        [
            'code' => 'tictactoe_unbeatable',
            'name' => 'Непобедимый',
            'description' => 'Заверши 5 игр в ничью в Крестики-Нолики',
            'icon' => 'bi-stars',
            'icon_type' => 'bootstrap',
            'category' => 'game',
            'condition_type' => 'game_event',
            'condition_value' => 5,
            'rarity' => 'rare',
            'sort_order' => 130,
        ],
        [
            'code' => 'collector',
            'name' => 'Коллекционер',
            'description' => 'Набери 1000 XP',
            'icon' => 'bi-collection-fill',
            'icon_type' => 'bootstrap',
            'category' => 'milestone',
            'condition_type' => 'xp_milestone',
            'condition_value' => 1000,
            'rarity' => 'rare',
            'sort_order' => 140,
        ],
        [
            'code' => 'spyfall_spy_win',
            'name' => 'Агент 007',
            'description' => 'Выграть партию за Шпиона',
            'icon' => 'bi-eye-slash-fill',
            'icon_type' => 'bootstrap',
            'category' => 'game',
            'condition_type' => 'game_event',
            'condition_value' => 1,
            'rarity' => 'uncommon',
            'sort_order' => 200,
        ],
        [
            'code' => 'spyfall_detective_win',
            'name' => 'Шерлок',
            'description' => 'Выиграть партию за Местного жителя',
            'icon' => 'bi-search',
            'icon_type' => 'bootstrap',
            'category' => 'game',
            'condition_type' => 'game_event',
            'condition_value' => 1,
            'rarity' => 'uncommon',
            'sort_order' => 210,
        ],
        [
            'code' => 'spyfall_vet',
            'name' => 'Ветеран Шпиона',
            'description' => 'Выиграть 5 партий в Шпиона',
            'icon' => 'bi-person-badge-fill',
            'icon_type' => 'bootstrap',
            'category' => 'game',
            'condition_type' => 'game_event',
            'condition_value' => 5,
            'rarity' => 'rare',
            'sort_order' => 220,
        ],
    ];
}

function seedAchievementDefinitions(PDO $pdo): int
{
    $stmt = $pdo->prepare("
        INSERT INTO achievements
            (code, name, description, icon, icon_type, category, condition_type, condition_value, rarity, sort_order)
        VALUES
            (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        ON DUPLICATE KEY UPDATE
            name = VALUES(name),
            description = VALUES(description),
            icon = VALUES(icon),
            icon_type = VALUES(icon_type),
            category = VALUES(category),
            condition_type = VALUES(condition_type),
            condition_value = VALUES(condition_value),
            rarity = VALUES(rarity),
            sort_order = VALUES(sort_order)
    ");

    $count = 0;
    foreach (getAchievementDefinitions() as $achievement) {
        $stmt->execute([
            $achievement['code'],
            $achievement['name'],
            $achievement['description'],
            $achievement['icon'],
            $achievement['icon_type'],
            $achievement['category'],
            $achievement['condition_type'],
            $achievement['condition_value'],
            $achievement['rarity'],
            $achievement['sort_order'],
        ]);
        $count++;
    }

    return $count;
}
